// Code generated by MockGen. DO NOT EDIT.
// Source: git/middleware/branch.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	git "github.com/libgit2/git2go/v31"
	middleware "github.com/neel1996/gitconvex/git/middleware"
)

// MockBranch is a mock of Branch interface.
type MockBranch struct {
	ctrl     *gomock.Controller
	recorder *MockBranchMockRecorder
}

// MockBranchMockRecorder is the mock recorder for MockBranch.
type MockBranchMockRecorder struct {
	mock *MockBranch
}

// NewMockBranch creates a new mock instance.
func NewMockBranch(ctrl *gomock.Controller) *MockBranch {
	mock := &MockBranch{ctrl: ctrl}
	mock.recorder = &MockBranchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBranch) EXPECT() *MockBranchMockRecorder {
	return m.recorder
}

// Cmp mocks base method.
func (m *MockBranch) Cmp(r middleware.Reference) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cmp", r)
	ret0, _ := ret[0].(int)
	return ret0
}

// Cmp indicates an expected call of Cmp.
func (mr *MockBranchMockRecorder) Cmp(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cmp", reflect.TypeOf((*MockBranch)(nil).Cmp), r)
}

// Delete mocks base method.
func (m *MockBranch) Delete() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete")
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBranchMockRecorder) Delete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBranch)(nil).Delete))
}

// IsNote mocks base method.
func (m *MockBranch) IsNote() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNote")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNote indicates an expected call of IsNote.
func (mr *MockBranchMockRecorder) IsNote() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNote", reflect.TypeOf((*MockBranch)(nil).IsNote))
}

// IsRemote mocks base method.
func (m *MockBranch) IsRemote() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRemote")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRemote indicates an expected call of IsRemote.
func (mr *MockBranchMockRecorder) IsRemote() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRemote", reflect.TypeOf((*MockBranch)(nil).IsRemote))
}

// IsTag mocks base method.
func (m *MockBranch) IsTag() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTag")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTag indicates an expected call of IsTag.
func (mr *MockBranchMockRecorder) IsTag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTag", reflect.TypeOf((*MockBranch)(nil).IsTag))
}

// Name mocks base method.
func (m *MockBranch) Name() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Name indicates an expected call of Name.
func (mr *MockBranchMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBranch)(nil).Name))
}

// Reference mocks base method.
func (m *MockBranch) Reference() middleware.Reference {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reference")
	ret0, _ := ret[0].(middleware.Reference)
	return ret0
}

// Reference indicates an expected call of Reference.
func (mr *MockBranchMockRecorder) Reference() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reference", reflect.TypeOf((*MockBranch)(nil).Reference))
}

// Target mocks base method.
func (m *MockBranch) Target() *git.Oid {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Target")
	ret0, _ := ret[0].(*git.Oid)
	return ret0
}

// Target indicates an expected call of Target.
func (mr *MockBranchMockRecorder) Target() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Target", reflect.TypeOf((*MockBranch)(nil).Target))
}
